[package]
name = "bashit"
version = "0.1.0"
authors = ["Matthew Charles Baker <mbaker@subspace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
resiter = "*"
lazy_static = "*"